version: "3"

services: 
  #
  #
  nginx:
    depends_on:
      - api
      - client
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    image: 'nginx:alpine'
    restart: always
    ports: 
      - '3000:80'

  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres_password
    image: 'postgres:10.5'
  #
  #
  redis:
    image: 'redis:latest'
  #
  #
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    stdin_open: true
    tty: true
    environment:
       # only for windows docker hosts or file changes are ignored
       - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
